Allow test to work on Java 25
Java 25 no longer allows jar:file:// URLs and will give errors like:

java.net.MalformedURLException: Unsupported non-local file URL

Now we must only use single / like jar:file:/